### ISSUE TITLE
Cannot sync files from Octoprint to Onedrive

### ISSUE THREAD

**Issue by RussPitcher** [cp2004/OctoPrint-OneDriveFileSync#11]
Installed version: 1.0.4 Development build 1

The sync currently isn't working for me.  I've currently set it to sync from OctoPrint to OneDrive to populate OneDrive with all my current files. I was then intending to reverse the sync so I could manage things easily from the PC but I haven't tried that yet.  I've tried unchecking the 'disable sync while printing' (I'm not printing) and also played with the automatic syncing checkbox and interval times.  When clicking the manual sync button it appears to respond but nothing gets copied.  the drop-down seems to refresh very quickly and the last sync time changes. However, if I do a Ctrl+F5 refresh or use a different browser the last sync time changes back to Never.

Any ideas?

Thanks for all your work on this :)

**Comment by cp2004** [comment]
First question, have you seen & are there any files in the 'OneDrive' folder that this plugin should have created in your file list. It will only sync files to this folder. This is in the readme but I will say it is not obvious so I can see how that might be overlooked, perhaps a note in the settings would be useful.

![image](https://user-images.githubusercontent.com/31997505/211346086-3e7c1890-d9e8-4eb5-9178-a9fe5984635d.png)

If you do have files in that folder, then please can you share a systeminfo bundle or just the `octoprint.log` file. It might help to enable debug level logging for the syncing:

![image](https://user-images.githubusercontent.com/31997505/211345667-dbcef3fb-7fe8-4fa8-a47d-cc8b3d2380dc.png)

Note it is the option that ends in .`sync`, you will also have `.api` and an option with no extra ending, but we `octoprint.plugins.onedrive_files.sync` is what you want there.

> However, if I do a Ctrl+F5 refresh or use a different browser the last sync time changes back to Never.

That's a slight bug, the last sync time is only ever sent to the frontend when it syncs - will make sure to fix that one to get it on page load too.

**Comment by RussPitcher** [comment]
Well that's embarrassing!

I clearly didn't read the readme correctly and in my excitement I'd assumed that the plugin would sync all the files and not only those in the /OneDrive folder (which I didn't notice).  As soon as I saw your image in the comment I realised what I had done.  Once I moved some files into that folder they quickly appeared on my OneDrive synced folder as expected.

You can chalk that one up to a user who should definitely know better!  Thanks again for your help.

**Comment by cp2004** [comment]
Good news 🙂. 1.0.4 includes an extra line in the 'Sync Folder' settings, to hopefully make this more clear.
Nobody ever properly reads the readme, so I would not be too embarrassed!
