### ISSUE TITLE
[Enhancement Request]: (I Can Help or Fork) - Dropbox sync for gcode files and timelapses

### ISSUE THREAD

**Issue by jviehmeyer** [cp2004/OctoPrint-OneDriveFileSync#14]
### Description of the bug

Hi Team, 

I was wondering if I could either fork the repo, and make it compatible with Dropbox, or if you guys might consider adding this as an option. I'd also love to see the Microsoft one backup gcode files, and Octoprint backups. Thanks!

### Plugin version

0

### OctoPrint version

0

### OctoPrint logs

N/A

**Comment by cp2004** [comment]
I won't be adding Dropbox sync to this plugin. It is entirely build around OneDrive and Microsoft's authentication methods. To switch it to Dropbox would be duplicating pretty much everything in this plugin, so it may as well be it's own plugin.

The [Dropbox Timelapse](https://github.com/jslay88/OctoPrint-Dropbox-Timelapse) plugin may be a better starting point. It can be configured to upload backups as well. You are of course always able to fork/take inspiration from this repo to make your own plugin if you would like to do so.

No team behind this plugin - just me in my spare time.

**Comment by jviehmeyer** [comment]
Thank you!!!!
