### ISSUE TITLE
not technically necessary

### ISSUE THREAD

**Issue by jcrposton** [cp2004/OctoPrint-OneDriveFileSync#16]
this capability is built into the ondrive app already. create a folder on onedrive devoted to your octoprint files and allow the onedrive app to sync all the files in the folder automatically. tell octoprint this is where you want uploads to go/where your files will be located(appdata\user\onedrive\xxx). anything you upload to octoprint will then be automatically quickly and easily synced to your onedrive without need for addons.

**Comment by jcrposton** [comment]
regardless, i respect your work and desire to learn.

**Comment by cp2004** [comment]
Is there a OneDrive app for Linux?

**Comment by jcrposton** [comment]
im not sure about linux or raspberry pi but the app is built heavily into windows and the android app works *almost* the same

**Comment by cp2004** [comment]
98% of all OctoPrint installs run Linux.

No need to be rude when you are misinformed.
