### ISSUE TITLE
[Bug]: due to some reason plugin stops sync after 700mb

### ISSUE THREAD

**Issue by viveksadhwani** [cp2004/OctoPrint-OneDriveFileSync#19]
### Description of the bug

installed multiple instance of octoprint onedrive sync plugin 
![image](https://user-images.githubusercontent.com/73689733/213746028-fbe0a60b-0338-451f-a839-0cd6fe87478c.png)

on all my printer due to some reason it stops sync at 700 mb and even after trying to manully sync by clicking sync now button it shows sync completed successfull 
![image](https://user-images.githubusercontent.com/73689733/213745446-28d826ae-854e-4a37-b2fd-8a53074569a7.png)

plugin should sync this folder 
![image](https://user-images.githubusercontent.com/73689733/213745765-687266eb-22a4-4d02-968a-4afb58be7d26.png)

config inside plugin setting 
![image](https://user-images.githubusercontent.com/73689733/213745907-66997f93-55be-42ea-a77c-1203081363c4.png)

this is happening with all my instance of octoprint onedrive sync plugin 

### Plugin version

OneDrive File Sync (1.0.5)

### OctoPrint version

Version 1.8.6

### OctoPrint logs

[plugin_pluginmanager_console.log](https://github.com/cp2004/OctoPrint-OneDriveFileSync/files/10467955/plugin_pluginmanager_console.log)
[octoprint.log](https://github.com/cp2004/OctoPrint-OneDriveFileSync/files/10467956/octoprint.log)

**Comment by cp2004** [comment]
This is a strange issue and the log doesn't seem to indicate any errors downloading files.

I did try my local install with a folder that claimed to have 1.3GB of gcode files, and once synced OctoPrint claimed it had just over 1GB files - so I might be able to reproduce some kind of issue here. I don't currently have time to dig into it, but will get to it as soon as I can.

**Comment by viveksadhwani** [comment]
i understand and respect your time / priorities , im not expert at programming, octoprint enviorment, plugin languages but this can a be an opporchunity to support this project by trying to see if same files are getting synced in all instance or different 

maybe by trying plugin different versions of octopi

maybe you can give me a task 

thanks 
have a good day

**Comment by cp2004** [comment]
I haven't had any ideas about why it seems that not everything is being synced. I could reproduce the issue so hopefully when I get a chance to look into the issue I can find it.

What would be interesting is if you can find the files that are not being synced (quite a manual process I appreciate) and see if it does happen the same all the time. I'll try and see if I can add some extra logging to the plugin that might help to debug the problem.

**Comment by viveksadhwani** [comment]
ok, i'll get to it

**Comment by viveksadhwani** [comment]
![image](https://user-images.githubusercontent.com/73689733/217028537-217f92cb-ff9a-4204-93e1-02567490deb3.png)
thinking creatively 
filtered by name ascending 
![image](https://user-images.githubusercontent.com/73689733/217028823-6dba49f5-bfc4-4283-864c-8050b6a014e3.png)
and then went to the botton of scroll 
and fond the below files to be 
![image](https://user-images.githubusercontent.com/73689733/217029061-a620fa85-1d74-465f-acb1-a12c43b39c3a.png)

now checked to all other octoprint instance and found same results 

now trying to download from one drive to check the file size
![image](https://user-images.githubusercontent.com/73689733/217031371-394f572c-1e81-4aff-8ee8-59d4ab9fb3f8.png)
after sorting it by name and ascending order

![image](https://user-images.githubusercontent.com/73689733/217033148-a1e833d4-1615-45e7-8864-686710d6b14e.png)
total 700 mb that means i found the files which are getting synced and now 

asking my self is it possible that its programmed in a way that only 200 files will get synced in a folder so tried to move remaining files to sub folder

and found theyre getting synced 

screen shot of the subfolder 
![image](https://user-images.githubusercontent.com/73689733/217033735-eba099cc-ea0d-4e56-8302-3129ba0d12e0.png)

screen shot of the main folder 
![image](https://user-images.githubusercontent.com/73689733/217033979-f26e378a-bcf8-47fd-8bc4-c2431105753c.png)

now im thinking if theres any way i can multi select from subfolder and move back to main folder for my programming to work 

any suggestion ?

**Comment by cp2004** [comment]
> asking my self is it possible that its programmed in a way that only 200 files will get synced in a folder so tried to move remaining files to sub folder

You're absolutely right here - I've just checked the API docs and there's a page limit of 200 items I didn't spot:

https://learn.microsoft.com/en-us/graph/api/driveitem-list-children?view=graph-rest-1.0&tabs=http#response

I guess I'll need to check and carry on requesting data until we get everything in the plugin. Thanks for looking through that, very helpful.

**Comment by viveksadhwani** [comment]
im just gonna install a plugin called multi select and update the files which didnt got synced

**Comment by viveksadhwani** [comment]
do you suggest i should close this issue ?

**Comment by cp2004** [comment]
No, leave it open and then it can be closed when the issue is actually fixed.

**Comment by cp2004** [comment]
Apologies for the delay here - the fix actually didn't take long but I never got around to it. I have just pushed a new release as 1.0.6 that I have tested & think fixes this issue. It might take up to 24 hours for your update notification to show up, or you can force-check in the software update settings.

Thanks for your patience!
