### ISSUE TITLE
Manual sync button?

### ISSUE THREAD

**Issue by Banner-Keith** [cp2004/OctoPrint-OneDriveFileSync#20]
I was wondering if you might be interested in adding a manual sync button on the main screen. For my workflow I am using this as an easy and quick way to upload gcode so my ideal scenario would be to be able to force a sync on demand. I would be happy to open a PR if you're not interested in putting time into this feature, although it may be slow going as I have zero experience with octoprint plugins.

**Comment by cp2004** [comment]
If you click the navbar icon, it is a manual sync button. If you hover over it, it looks like this:


![Image](https://user-images.githubusercontent.com/31997505/214314339-209e2e3a-2a9c-4ad5-a5e6-10390da0cfc4.png)

**Comment by Banner-Keith** [comment]
Oh awesome. Thank you.
