### ISSUE TITLE
[Feature Request] Add Sync Now button

### ISSUE THREAD

**Issue by Grahamvs** [cp2004/OctoPrint-OneDriveFileSync#23]
This is a great plugin, but I'm having a slight issue in that I've set the sync time to 60 seconds, but it's not updating when expected.

While this is more likely a bug, it raised the idea of having a "Sync Now" button so I can revert the sync time back to 1 hour and force an update as needed. I often want to copy a gcode file to my OneDrive and start printing almost immediately, so this would be really useful.

**Comment by cp2004** [comment]
I seriously thought I replied to this before... You can click the cloud icon in the navbar, and it should trigger a sync straight away.

**Comment by Grahamvs** [comment]
Thanks, I'll take a look when I get back into printing (taking a break at the moment as I'm frustrated with my printer, lol)
