### ISSUE TITLE
Can't update the sync folder[Bug]: 

### ISSUE THREAD

**Issue by roelfsre** [cp2004/OctoPrint-OneDriveFileSync#7]
### Description of the bug

In the settings I want to set the Sync Folder, but it does not allow me to do this. No error message, but when I click on "Set Sync Folder" it does not do this. It keeps telling me: Currently configured sync folder: None

### Plugin version

1.0.3

### OctoPrint version

1.8.6

### OctoPrint logs

[octoprint-systeminfo-20230108183237.zip](https://github.com/cp2004/OctoPrint-OneDriveFileSync/files/10369185/octoprint-systeminfo-20230108183237.zip)

**Comment by cp2004** [comment]
Thank you for filling in a full bug report with the system info bundle included 👍.

I believe I've fixed this issue - please could you test the development version. You should be able to get it either through switching to 'Release Candidate' in the software update settings for this plugin, or by using the below URL in the plugin manager > get more > ...from URL area:

```
https://github.com/cp2004/OctoPrint-OneDriveFileSync/releases/download/1.0.4.dev1/release.zip
```

**Comment by cp2004** [comment]
1.0.4 has been released, fixing a number of issues including this one.
